@startuml
control githudd
control fetcher
database MVar
control listener
control reader

-> githudd : CLI invocation
githudd -> githudd : parse arguments
githudd -> githudd : get Config

alt Fetcher not running
  githudd -> fetcher : Launch
  fetcher -> MVar : Create MVar\nPut current path in it
  fetcher -> listener : Open socket
  group forever
    listener -> listener : Accept
  end
else standard
  githudd -> listener : Post message on socket
  listener -> reader : Create
  reader -> reader : Read socket
  reader -> MVar : Update MVar
end

group forever
  MVar -> fetcher : Read MVar for path
  fetcher -> : git fetch path
end
@enduml
